spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: careningra@gmail.com
    password: dxfc oebr nszx ilcj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs.path: /api-docs